### ISSUE TITLE
Build failure - missing file Dilithium/BitStreamReader.hpp

### ISSUE THREAD

**Issue by dnovillo** [gongminmin/Dilithium#7]
@gongminmin I've started testing Dilithium on Linux.  We are interested in exploring DXIL<->SPIRV conversion and would likely contribute in the future.

I'm finding several build errors (the code seems quite out-of-date).  One of them is a missing header file `fatal error: 'Dilithium/BitStreamReader.hpp' file not found`.

At a higher level, I'm wondering whether you have a plan for missing features and an idea of how much more would be needed to get at least the DXIL -> SPIRV part going.

Thanks!  Diego.

**Comment by gongminmin** [comment]
This project is actually suspended. I haven't work on it for years. During my investigation of DXIL to SPIRV, I found a lot of missing pieces. So later on I moved forward to https://github.com/Microsoft/ShaderConductor.

**Comment by dnovillo** [comment]
Thanks for the update!
